### ISSUE TITLE
JSON decoding error when visiting "Sources"

### ISSUE THREAD

**Issue by squaremo** [fluxcd/webui#21]
Using main@e17fc118e336accd370a326c388e5241efec6f69 and following the instructions in the README, I see this when I go to the Sources tab, while pointing at a newly-flux-bootstrapped cluster:

```
Error

There was an error fetching sources
Error: the json request could not be decoded
```

(it said the same thing when the cluster wasn't flux-bootstrapped).

**Comment by jpellizzari** [comment]
Found this myself yesterday. Working on it now.

**Comment by jpellizzari** [comment]
This commit appears to be to blame: https://github.com/fluxcd/webui/pull/17/commits/51aaf00d3913348710a5227f28827a397b1d18fd

Related: https://github.com/larrymyers/protoc-gen-twirp_typescript/issues/61
