### ISSUE TITLE
assets.go is regenerated when building in a pristine repo

### ISSUE THREAD

**Issue by squaremo** [fluxcd/webui#22]
When I run `make dev` in a pristine checkout, `pkg/assets/assets.go` is regenerated, and different. This is problematic because it means any change is going to be accompanied by a giant, impenetrable diff of `assets.go`.

Typically you would expect this to be avoided in the Makefile by `pkg/assets/assets.go` depending on the files that are included in it, so if they are not newer than `assets.go`, the generation is not run. It's possible Go 1.16's inbuilt filesystem utils would sidestep the problem.

**Comment by jpellizzari** [comment]
Related: https://github.com/fluxcd/webui/issues/3
