### ISSUE TITLE
"Add to HelmRelease" for HelmReleases

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/webui#33]
Should say instead "Add to HelmRelease" - this should work almost exactly like the existing workflow for other "workloads"

The behavior where unmanaged workloads have a call to action that allows you to add them to Flux as a Flux Kustomization, but do the same thing for unmanaged Helm Releases. All of the information about the release is already present in a configmap that `helm install` stores for each release in the history. It should work basically the same way.

The only thing you need the user to provide is the source repository URL, since helm doesn't apparently store that (and there is a possibility that it might not exist, you can do helm install from a chart that you have stored locally in your workstation. We won't be able to slurp those helm releases, but there probably won't be many users who have trouble understanding this.)

The release name, namespace, values can all be inferred by reading the values stored in the configmap (there is `helm get values [releasename]` which you can use to inspect them from the helm client).

(This idea came up during today's Flux/GOTK WW meeting)

**Comment by jpellizzari** [comment]
This is no longer relevant, as the "workloads" section has been removed.
