### ISSUE TITLE
Unable to "make dev" as per README.md

### ISSUE THREAD

**Issue by chrisk700** [fluxcd/webui#44]
Hi,

I'm not sure if this is something I've not followed correctly but following the README.md:

> 6. `make dev` to compile and run the app

````
> webui > make dev
reflex -r '.go' -s -- sh -c 'go run main.go'
[00] Starting service
[00] main.go:90:12: pattern dist/*: no matching files found
[00] (error exit: exit status 1)
````

After running:

> 7. `npm start` to start the frontend dev server (with hot-reloading)

this was fine but the process had already exited.

Is it acceptable to run `npm start` first and then `make dev` once `Built in xx.xxs.` is reported?

**Comment by jpellizzari** [comment]
@chrisk700 The new(ish) go embedding strategy relies on the files being there ahead of time. I think some `Makefile` wizardry can solve this.

Thanks for the report!
