### ISSUE TITLE
Error: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by brianpham** [fluxcd/webui#52]
**Describe the bug**
I see the following error, but not too sure if its a bug or if I am missing a configuration somewhere. 
```
There was an error fetching namespaces
could not create client: kubernetes client initialization failed: no Auth Provider found for name "gcp"
```

**To Reproduce**
1. Download https://github.com/fluxcd/webui/releases/download/v0.1.0/flux-webui_0.1.0_darwin_amd64.tar.gz
2. Extract and run `./flux-webui`
3. Navigate to http://localhost:9000

**Expected behavior**

**Screenshots**
<img width="974" alt="Screen Shot 2021-06-10 at 10 50 55 AM" src="https://user-images.githubusercontent.com/5695495/121573171-c8ddd700-c9d9-11eb-98ea-ca492502c6d8.png">

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur 11.2.3 (20D91)]
 - Browser [chrome]
 - Version [91.0.4472.101]

**Comment by stefanprodan** [comment]
This should fix it https://github.com/fluxcd/flux2/blob/main/cmd/flux/main.go#L26
